### ISSUE TITLE
CPU pegged by debuggerd on startup, related to radio stack (exarcerbated by lack of SIM)

### ISSUE THREAD

**Issue by jlebar** [andreasgal/B2G#47] opened 2011-10-21 19:32 UTC
```
D/CallManager( 5807): registerPhone(GSM Handler{405b4638})
W/ActivityManager( 3186): Timeout executing service: ServiceRecord{40696e60 com.android.phone/.BluetoothHeadsetService}
I/Process ( 3186): Sending signal. PID: 5807 SIG: 3
I/dalvikvm( 5807): threadid=4: reacting to signal 3
I/dalvikvm( 5807): Wrote stack traces to '/data/anr/traces.txt'
I/Process ( 3186): Sending signal. PID: 3186 SIG: 3
I/dalvikvm( 3186): threadid=4: reacting to signal 3
I/dalvikvm( 3186): Wrote stack traces to '/data/anr/traces.txt'
I/Process ( 3186): Sending signal. PID: 3310 SIG: 3
I/dalvikvm( 3310): threadid=4: reacting to signal 3
I/dalvikvm( 3310): Wrote stack traces to '/data/anr/traces.txt'
I/Process ( 3186): Sending signal. PID: 3268 SIG: 3
I/dalvikvm( 3268): threadid=4: reacting to signal 3
I/dalvikvm( 3268): Wrote stack traces to '/data/anr/traces.txt'
D/dalvikvm( 3186): GC_EXPLICIT freed 1032K, 46% free 4612K/8519K, external 2873K/3338K, paused 40ms
I/Process ( 3186): Sending signal. PID: 5807 SIG: 9
E/ActivityManager( 3186): ANR in com.android.phone
E/ActivityManager( 3186): Reason: Executing service com.android.phone/.BluetoothHeadsetService
E/ActivityManager( 3186): Load: 1.26 / 1.23 / 1.18
E/ActivityManager( 3186): CPU usage from 15037ms to 0ms ago:
E/ActivityManager( 3186):   98% 2577/debuggerd: 10% user + 87% kernel
E/ActivityManager( 3186):   2.2% 3310/org.mozilla.fennec_jlebar: 1.2% user + 0.9% kernel
E/ActivityManager( 3186):   0.8% 1448/mmcqd: 0% user + 0.8% kernel
E/ActivityManager( 3186):   0.1% 2671/flush-179:0: 0% user + 0.1% kernel
E/ActivityManager( 3186):   0.1% 3186/system_server: 0% user + 0% kernel
E/ActivityManager( 3186):   0% 9/events/0: 0% user + 0% kernel
E/ActivityManager( 3186):   0% 525/kondemand/0: 0% user + 0% kernel
E/ActivityManager( 3186):   0% 546/kswapd0: 0% user + 0% kernel
E/ActivityManager( 3186):   0% 1268/file-storage: 0% user + 0% kernel
E/ActivityManager( 3186):   0% 2566/jbd2/mmcblk0p10: 0% user + 0% kernel
E/ActivityManager( 3186): 50% TOTAL: 5.7% user + 44% kernel + 0.1% iowait
E/ActivityManager( 3186): CPU usage from 137ms to 651ms later:
E/ActivityManager( 3186):   100% 2577/debuggerd: 13% user + 86% kernel
E/ActivityManager( 3186):   1.9% 3186/system_server: 0% user + 1.9% kernel
E/ActivityManager( 3186):     3.9% 3200/ActivityManager: 1.9% user + 1.9% kernel
E/ActivityManager( 3186):   1.6% 3310/org.mozilla.fennec_jlebar: 0% user + 1.6% kernel
E/ActivityManager( 3186):     1.6% 3376/Thread-12: 0% user + 1.6% kernel
E/ActivityManager( 3186):     1.6% 3406/Thread-12: 0% user + 1.6% kernel
E/ActivityManager( 3186): 51% TOTAL: 7.6% user + 44% kernel
W/DropBoxManagerService( 3186): Dropping: system_app_anr (10 > 0 bytes)
I/ActivityManager( 3186): Process com.android.phone (pid 5807) has died.
I/ServiceManager( 2574): service 'isms' died
I/ServiceManager( 2574): service 'simphonebook' died
I/ServiceManager( 2574): service 'iphonesubinfo' died
I/ServiceManager( 2574): service 'phone' died
W/ActivityManager( 3186): Canceling start item Intent { cmp=com.android.phone/.BluetoothHeadsetService } in service ComponentInfo{com.android.phone/com.android.phone.BluetoothHeadsetService}
W/ActivityManager( 3186): Scheduling restart of crashed service com.android.phone/.BluetoothHeadsetService in 41366ms
I/ActivityManager( 3186): Start proc com.android.phone for restart com.android.phone: pid=5825 uid=1001 gids={3002, 3001, 3003, 1015}
D/dalvikvm( 3176): GC_EXPLICIT freed 13K, 50% free 2716K/5379K, external 1625K/2137K, paused 30ms
D/dalvikvm( 3176): GC_EXPLICIT freed <1K, 50% free 2716K/5379K, external 1625K/2137K, paused 19ms
D/dalvikvm( 3176): GC_EXPLICIT freed <1K, 50% free 2716K/5379K, external 1625K/2137K, paused 37ms
I/ActivityThread( 5825): Pub mms: com.android.providers.telephony.MmsProvider
I/ActivityThread( 5825): Pub sms: com.android.providers.telephony.SmsProvider
I/ActivityThread( 5825): Pub telephony: com.android.providers.telephony.TelephonyProvider
I/ActivityThread( 5825): Pub icc: com.android.phone.IccProvider
I/ActivityThread( 5825): Pub mms-sms: com.android.providers.telephony.MmsSmsProvider
D/CallManager( 5825): registerPhone(GSM Handler{405b4b00})
```

It then hangs at registerPhone for 20s or so.

**Comment by jlebar** [comment] 2011-10-21 19:35
I also had 1.88gb in the one file in /data/tombstones.  I deleted this file, but the high CPU usage persists.

**Comment by joneschrisg** [comment] 2011-10-22 00:20
Odd, I haven't seen this.  Did you do anything in particular that seemed to trigger it?

**Comment by jlebar** [comment] 2011-10-22 01:06
I booted my phone for the first time (it finally works!), clicked a few apps which weren't implemented, and then left the phone in sleep mode.  I noticed that it was getting very warm, so I opened logcat and captured the trace above.

**Comment by joneschrisg** [comment] 2011-10-22 01:13
Strange.  And if you put in a SIM card, the problems go away?

**Comment by jlebar** [comment] 2011-10-22 01:14
I'm kind of scared to put my SIM in this phone.  It's not going to do something bad?

**Comment by joneschrisg** [comment] 2011-10-22 01:16
Can't promise anything :).  Nothing bad reported from others so far.

**Comment by shianyow** [comment] 2011-10-22 09:45
One my S2 phone it's also hot.
There is a process "/system/bin/debuggerd" with 49.4% CPU usage and I have to kill this process to cool down the phone.

**Comment by andreasgal** [comment] 2011-10-22 10:04
@jlebar I used my SIM in the few times, no issues. If you are worried buy and expense a prepaid sim.

**Comment by jlebar** [comment] 2011-10-23 20:13
This is reproducible for me on my Galaxy S II.  When I have a SIM
onboard, I don't get these exceptions and the phone stays cool.  When
I shut down, take out the SIM, and reboot, one CPU is pegged at ~10%
user ~90% kernel.

E/ActivityManager( 2681): CPU usage from 15050ms to 0ms ago:
E/ActivityManager( 2681):   99% 2578/debuggerd: 9.1% user + 90% kernel
E/ActivityManager( 2681):   0.8% 1448/mmcqd: 0% user + 0.8% kernel
E/ActivityManager( 2681):   0.1% 2671/flush-179:0: 0% user + 0.1% kernel
E/ActivityManager( 2681):   0% 2681/system_server: 0% user + 0% kernel
/ faults: 3 minor
E/ActivityManager( 2681):   0% 2753/com.android.systemui: 0% user + 0%
kernel / faults: 10 minor
E/ActivityManager( 2681): 50% TOTAL: 4.6% user + 45% kernel + 0.1% iowait
E/ActivityManager( 2681): CPU usage from 122ms to 635ms later:
E/ActivityManager( 2681):   101% 2578/debuggerd: 9.8% user + 92% kernel
E/ActivityManager( 2681):   3.9% 2681/system_server: 0% user + 3.9% kernel
E/ActivityManager( 2681):     1.9% 2698/ActivityManager: 0% user + 1.9% kernel
E/ActivityManager( 2681): 50% TOTAL: 3.9% user + 47% kernel

On Sat, Oct 22, 2011 at 6:04 AM, Andreas Gal
reply@reply.github.com
wrote:

**Comment by joneschrisg** [comment] 2011-10-25 01:05
It would be interesting to see what debuggerd is doing that's chewing all this CPU (busy wait for gdb?  wouldn't put it past android ...), but this bug isn't very high priority.  I also suspect it would go away if USB debugging was disabled, but then it would be difficult to test.  (I'm also slightly interested in whether this happens in commercial android builds, but I don't have the patience to try atm.)

**Comment by joneschrisg** [comment] 2011-11-02 06:58
I can reproduce the same problem _with_ a SIM card present.  The problem looks like a bad startup order in something related to the radio stack.  While debuggerd is spinning, my radio is unusable.  If I kill it, the radio turns on.

**Comment by shianyow** [comment] 2011-11-08 14:13
According to /data/tombstone, it was triggered by crash (SIGBUS) of /system/bin/mediaserver during startup.
After killing pid of spinning debuggerd, it recovered temporarily.  But it may happen again if some process crashed.
For example, if we send SIGBUS (by kill -7) to pid of /system/bin/mediaserver twice, the problem can be reproduced again.  Doing same thing to /system/bin/rild can reproduce it as well.

When debuggerd spinning, it keeps dumping log to /data/tombstone.  According to the tombstone content, seems it's trying to dump whole address space, which would eventually exhaust space of /data partition.

I think there are 2 issues to solve:
1. /system/bin/mediaserver crash during system booting.  Fixing this should let go of frequent CPU peg on startup.
2. spinning debuggerd.  This is the actual issue to be fixed.  I ever tried to replacing with the debuggerd pulled from S2 stock frimware, but doesn't help.

**Comment by andreasgal** [comment] 2011-11-08 15:44
This is some fine debugging work, thanks. We should fix both issues. Debuggerd should never spin like that. And the media server shouldn't crash. Let's split the issue in 2 bugs.

**Comment by shianyow** [comment] 2011-11-08 16:06
When process crashed, system/core/debuggerd/debuggerd.c will dump stack content in function dump_stack_and_code().
In debuggerd spinning case, the stack end value is 0xbe808b20, and p value is 0x40567dc0(far from stack end), causing it to take long time to finish dumping and it will eventually exhaust /data/tombsone space.

It seems something wrong of the stack end value retrieved from sp_list[unwind_depth-1].
Need further tracing on this issue...

```
p = sp - 64;
p &= ~3;
if (unwind_depth != 0) {
    if (unwind_depth < STACK_CONTENT_DEPTH) {
        end = sp_list[unwind_depth-1];
    }
    else {
        end = sp_list[STACK_CONTENT_DEPTH-1];
    }
}
else {
    end = sp | 0x000000ff;
    end += 0xff;
}

_LOG(tfd, only_in_tombstone, "\nstack:\n");

/* If the crash is due to PC == 0, there will be two frames that
 * have identical SP value.
 */
if (sp_list[0] == sp_list[1]) {
    sp_depth = 1;
}
else {
    sp_depth = 0;
}

while (p <= end) {
     char *prompt;
     char level[16];
     data = ptrace(PTRACE_PEEKTEXT, pid, (void*)p, NULL);
     if (p == sp_list[sp_depth]) {
         sprintf(level, "#%02d", sp_depth++);
         prompt = level;
     }
     else {
         prompt = "   ";
     }

     /* Print the stack content in the log for the first 3 frames. For the
      * rest only print them in the tombstone file.
      */
     _LOG(tfd, (sp_depth > 2) || only_in_tombstone,
          "%s %08x  %08x  %s\n", prompt, p, data,
          map_to_name(map, data, ""));
     p += 4;
}
```

**Comment by shianyow** [comment] 2011-11-09 14:11
Current dump_stack_and_code() in debuggerd.c sets "end" value to the last address in sp_list[], without checking its validity.  Stack trace addresses in sp_list[] should be within similar address space.  In error case, the last address was strange, like the example below in sp_list[9].
sp_list[0]=40467e00
sp_list[1]=40467e08
sp_list[2]=40467e28
sp_list[3]=40467e60
sp_list[4]=40467e90
sp_list[5]=40467ea0
sp_list[6]=40467ec8
sp_list[7]=40467ee8
sp_list[8]=40467f00
sp_list[9]=beb77b20

Why the stack pointer invalid is not yet known, but it won't happen if we use "libc.so" pulled from S2 firmware.
Could it be related compatibility between different shared libraries mixed by S2 and Android AOSP?

Anyway, debuggerd should not dump stack using invalid end address.
Below change sets end value to last valid address, and it will fix the debuggerd spinning issue.

```
diff --git a/debuggerd/debuggerd.c b/debuggerd/debuggerd.c
index b557cea..795c21b 100644
--- a/debuggerd/debuggerd.c
+++ b/debuggerd/debuggerd.c
@@ -125,7 +125,6 @@ void dump_build_info(int tfd)
     _LOG(tfd, false, "Build fingerprint: '%s'\n", fingerprint);
 }

-
 void dump_stack_and_code(int tfd, int pid, mapinfo *map,
                          int unwind_depth, unsigned int sp_list[],
                          bool at_fault)
@@ -191,12 +190,30 @@ void dump_stack_and_code(int tfd, int pid, mapinfo *map,
     p = sp - 64;
     p &= ~3;
     if (unwind_depth != 0) {
+#if 1
+        #define MAX_STACK_SIZE 65536
+        int i;
+
+        /* Checking sp_list, and setting end value to last valid stack pointer */
+        for(i = 1; i < unwind_depth; i++)
+        {
+            if( (sp_list[i] - sp_list[i - 1]) > MAX_STACK_SIZE) {
+                _LOG(tfd, only_in_tombstone, "\nInvalid stack pointer: sp_list[%d]=%08x\n", i, sp_list[i]);
+                break;
+            }
+            if(i == STACK_CONTENT_DEPTH) {
+                break;
+            }
+        }
+        end = sp_list[i-1];
+#else
         if (unwind_depth < STACK_CONTENT_DEPTH) {
             end = sp_list[unwind_depth-1];
         }
         else {
             end = sp_list[STACK_CONTENT_DEPTH-1];
         }
+#endif
     }
     else {
         end = sp | 0x000000ff;
```

**Comment by joneschrisg** [comment] 2011-11-09 18:30
We're building with a different configuration (no-thumb and a few other minor changes) than stock android.  We have a different build config so that we can get better profiling info.  It's likely that this is a bug in debuggerd that doesn't get exercised by stock builds.

Did you check to see if there's a fix in cyanogenmod?  I would guess probably not, since they use the same build options as stock, but it's worth a look.

Nice work!

**Comment by shianyow** [comment] 2011-11-10 02:50
Yes, I ever checked CM, but no related fix.  And I didn't find others mentioned similar issue on debuggerd.  

As to /system/bin/mediaserver initial crash, I will open another issue to separate from debuggerd spinning.

**Comment by joneschrisg** [comment] 2011-11-10 19:53
@shianyow I forked system/core (https://github.com/cgjones/android-system-core) so let's get the debugger patch landed.  I don't see a need for the #if/#else if the patch is correct.  This is something we should try to upstream as well (later ;).

**Comment by shianyow** [comment] 2011-11-12 07:20
Landed to b2g-gingerbread branch of system-core, seems it's stable branch for b2g at this moment.
The master branch cannot be compiled due to missing including file "ipv6_route.h", which only available in newer bionic revision.

**Comment by joneschrisg** [comment] 2011-11-15 01:55
@shianyow Do you mind merging the system/core fix into the main b2g repo?

**Comment by joneschrisg** [comment] 2011-11-15 06:14
@shianyow since this specific debuggerd problem is now fixed, and the remaining work is tracked in #56, would you like to close this issue?

**Comment by shianyow** [comment] 2011-11-15 11:10
@cgjones Yes, I think this issue should be closed.  Could you close it for me?  I don't have the privilege to close it.

**Closed as completed** 2011-11-15 17:16 UTC

**Comment by joneschrisg** [comment] 2011-11-16 00:18
Ugh, sorry.  Working on getting that fixed.
